input:
  csv:
    paths: [./test.csv]
    parse_header_row: true
    delimiter: ','

pipeline:
  processors:
    - bloblang: |
        root = "INSERT INTO users(name) VALUES ('%s');".format(this.foo)
        #root.foo = this.foo.uppercase()
        #root.bar = this.bar
    - catch:
        - log:
            message: "Processing failed due to: ${!error()}"

output:
  switch:
    cases:
      # When the environment variable dry_run=true, then print to stdout.
      - check: env("dry_run") == "true"
        output:
          type: stdout
      # Else, write to sql.
      - output:
          file:
            path: "./out.sql"
            codec: lines
