# Only logs error
logger:
  level: ERROR
  format: classic # Option: logfmt, classic, json

input:
  csv:
    paths: ["./*.csv"]
    parse_header_row: true
    delimiter: ','

pipeline:
  processors:
    - resource: row_proc

processor_resources:
  - label: row_proc
    bloblang: |
      import "./process_row.blobl"
      root = this.apply("process_row")

output:
  switch:
    cases:
      # Skip if there is error.
      - check: errored()
        output:
          stdout:
            delimiter: ""
      - output:
          file:
            path: "./out.sql"
            codec: "lines"
